### ISSUE TITLE
bug:若工作VSCODE工作空间有多个文件夹时，mock文件夹默认创建到第一个文件夹。

### ISSUE THREAD

**Issue by good1uck** [Elity/EasyMock-VSCode#3]
当前，若工作VSCODE工作空间有多个文件夹时，mock文件夹默认创建到第一个文件夹，并提示已在当前工作创建。

bug是，移出第一个文件夹后，重启esaymock服务，依然会继续在第一个文件夹创建。

**Comment by Elity** [comment]
@good1uck  已经解决，请更新easy mock 至1.0.14版本
