### ISSUE TITLE
匹配的url 支持正则匹配路径吗？ 应该怎么写？

### ISSUE THREAD

**Issue by spiritelf** [Elity/EasyMock-VSCode#5]

**Comment by Elity** [comment]
从[代码](https://github.com/Elity/EasyMock-VSCode/blob/d578e0239cb6047f8790b74f008700596a69dcd7/src/mock.js#L102)看，支持 express 的匹配模式  https://www.expressjs.com.cn/guide/routing.html
你先试试， 有问题再反馈

**Comment by spiritelf** [comment]
> 从[代码](https://github.com/Elity/EasyMock-VSCode/blob/d578e0239cb6047f8790b74f008700596a69dcd7/src/mock.js#L102)看，支持 express 的匹配模式 https://www.expressjs.com.cn/guide/routing.html
> 你先试试， 有问题再反馈

怎么传参数呢  
 'post /api/changeInfo': {
    message: 'success',
    status: 0,
  }

**Comment by Elity** [comment]
> > 从[代码](https://github.com/Elity/EasyMock-VSCode/blob/d578e0239cb6047f8790b74f008700596a69dcd7/src/mock.js#L102)看，支持 express 的匹配模式 https://www.expressjs.com.cn/guide/routing.html
> > 你先试试， 有问题再反馈
> 
> 怎么传参数呢
> 'post /api/changeInfo': {
> message: 'success',
> status: 0,
> }

类似于这样：
```js

"post /ab*cd": {
    xxxx
}
```
